version: '3.8'

services:
  backend:
    build: .
    image: ${DOCKERHUB_USERNAME:-b3njii}/rentasauto:latest
    container_name: rentasauto-app
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: rentasauto-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rentcar_db
      MYSQL_USER: rentcar_user
      MYSQL_PASSWORD: rentcar_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: